from typing import Any

def show(*objs: Any, **kwargs: Any) -> Any: ...
def show_object(*objs: Any, **kwargs: Any) -> Any: ...
def show_objects(*objs: Any, **kwargs: Any) -> Any: ...
def show_all(**kwargs: Any) -> Any: ...
def show_clear() -> None: ...
def reset_show() -> None: ...
def remove_object(name: str, **kwargs: Any) -> Any: ...
def push_object(*objs: Any, **kwargs: Any) -> Any: ...
def save_screenshot(filename: str, **kwargs: Any) -> Any: ...
